few_shot_config = {
    "random_seed": 3,
    "OutputFile": "/home/aml7990/Code/creativity-item-generation/scorers/CPS/LLM/outputs/gpt-3.5-turbo/",
    "logFile": "/home/aml7990/Code/creativity-item-generation/scorers/CPS/LLM/outputs/gpt-3.5-turbo/log.txt",
    "dataset": "/home/aml7990/Code/creativity-item-generation/datasets/cps/cleaned/CPSTfulldataset3-standarized.csv",
    "ModelName": "asst_zWA8oQ7R1NuITqZNG8Q9boEv",
    "TrainItem": "Becky",
    "TokenizerName": "openai",
    "MaxTokens": 2048,
    "Temperature": 0.0,
    "TopP": 1.0,
    "NumShots": 20,
    "PromptIdx": 0,
    "use_sweep": False,
    "use_test_set": False,
}