few_shot_config = {
    "random_seed": 3,
    "OutputFile": "/home/aml7990/Code/creativity-item-generation/scorers/CPS/LLM/outputs/claude-3/",
    "logFile": "/home/aml7990/Code/creativity-item-generation/scorers/CPS/LLM/outputs/claude-3/log.txt",
    "dataset": "/home/aml7990/Code/creativity-item-generation/datasets/cps/cleaned/CPSTfulldataset3-standarized.csv",
    "ModelName": "claude-3",
    "TrainItem": "Ralph",
    "TokenizerName": "openai",
    "MaxTokens": 2048,
    "Temperature": 0.0,
    "TopP": 1.0,
    "NumShots": 10,
    "PromptIdx": 1,
    "use_sweep": False,
    "use_test_set": False,
}